### ISSUE TITLE
Add support for relative paths 

### ISSUE THREAD

**Issue by matanui159** [jantimon/favicons-webpack-plugin#177] opened 2019-11-14 21:36 UTC
Would help in situations like gitlab pages where it's usually in a subfolder

Apparently `manifest.json` does support relative paths as well

**Comment by Tofandel** [comment] 2019-11-21 11:11
This is basically a duplicate of https://github.com/jantimon/favicons-webpack-plugin/issues/162

If it wasn't for this issue, the plugin would support relative path

**Comment by jantimon** [comment] 2019-12-28 08:10
Fixed and released as https://www.npmjs.com/package/favicons-webpack-plugin/v/2.0.0

**Closed by jantimon** 2019-12-28 08:10 UTC
