### ISSUE TITLE
favicons-webpack-plugin v3.0.1 incompatible with html-webpack-plugin v4.0.4?

### ISSUE THREAD

**Issue by yvza** [jantimon/favicons-webpack-plugin#198] opened 2020-04-07 08:55 UTC
im on fresh vue cli project, and going to implement this plugin, but i got this error, how to solve that?

vue.config.js
![errImage 1](https://user-images.githubusercontent.com/25668079/78649597-dbe1ac80-78e7-11ea-9d0e-661393bd5e86.png)

package.json
![erImage 2](https://user-images.githubusercontent.com/25668079/78649755-15b2b300-78e8-11ea-91e3-bba2a53b5dba.png)

**Comment by jantimon** [comment] 2020-04-07 13:07
Oh that's strange 😨

**Comment by yvza** [comment] 2020-04-12 12:57
hi @jantimon, sorry for my late response, so yesterday for quick fix i just downgrade `favicons-webpack-plugin` version to 2.1.0

and here is `node_modules/html-webpack-plugin/package.json` look like
```
{
  "_from": "html-webpack-plugin",
  "_id": "html-webpack-plugin@4.0.4",
  "_inBundle": false,
  "_integrity": "sha512-BREQzUbFfIQS39KqxkT2L1Ot0tuu1isako1CaCQLrgEQ43zi2ScHAe3SMTnVBWsStnIsGtl8jprDdxwZkNhrwQ==",
  "_location": "/html-webpack-plugin",
  "_phantomChildren": {
    "define-properties": "1.1.3",
    "object.getownpropertydescriptors": "2.1.0"
  },
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "html-webpack-plugin",
    "name": "html-webpack-plugin",
    "escapedName": "html-webpack-plugin",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#DEV:/",
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/html-webpack-plugin/-/html-webpack-plugin-4.0.4.tgz",
  "_shasum": "90cdfb168094e93e047174d9baca098ec5540636",
  "_spec": "html-webpack-plugin",
  "_where": "C:\\wamp64\\www\\everything\\home\\4.LatihanWEB\\81.domain-parking",
  "author": {
    "name": "Jan Nicklas",
    "email": "j.nicklas@me.com",
    "url": "https://github.com/jantimon"
  },
  "bugs": {
    "url": "https://github.com/jantimon/html-webpack-plugin/issues"
  },
  "bundleDependencies": false,
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "dependencies": {
    "@types/html-minifier-terser": "^5.0.0",
    "@types/tapable": "^1.0.5",
    "@types/webpack": "^4.41.8",
    "html-minifier-terser": "^5.0.1",
    "loader-utils": "^1.2.3",
    "lodash": "^4.17.15",
    "pretty-error": "^2.1.1",
    "tapable": "^1.1.3",
    "util.promisify": "1.0.0"
  },
  "deprecated": false,
  "description": "Simplifies creation of HTML files to serve your webpack bundles",
  "devDependencies": {
    "@types/loader-utils": "1.1.3",
    "@types/node": "11.13.9",
    "appcache-webpack-plugin": "1.4.0",
    "commitizen": "4.0.3",
    "css-loader": "2.1.1",
    "cz-conventional-changelog": "2.1.0",
    "dir-compare": "1.7.2",
    "file-loader": "3.0.1",
    "html-loader": "0.5.5",
    "jest": "24.7.1",
    "mini-css-extract-plugin": "0.6.0",
    "pug": "2.0.3",
    "pug-loader": "2.4.0",
    "rimraf": "2.6.3",
    "semistandard": "13.0.1",
    "standard-version": "5.0.2",
    "style-loader": "0.23.1",
    "typescript": "3.5.2",
    "webpack": "4.35.2",
    "webpack-recompilation-simulator": "3.0.0"
  },
  "engines": {
    "node": ">=6.9"
  },
  "files": [
    "lib/",
    "index.js",
    "default_index.ejs",
    "typings.d.ts"
  ],
  "homepage": "https://github.com/jantimon/html-webpack-plugin",
  "jest": {
    "watchPathIgnorePatterns": [
      "<rootDir>/dist"
    ],
    "testEnvironment": "node"
  },
  "keywords": [
    "webpack",
    "plugin",
    "html",
    "html-webpack-plugin"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "html-webpack-plugin",
  "peerDependencies": {
    "webpack": "^4.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jantimon/html-webpack-plugin.git"
  },
  "scripts": {
    "build-examples": "node examples/build-examples.js",
    "commit": "git-cz",
    "posttest": "tsc",
    "pretest": "semistandard",
    "puml": "npx puml generate flow.puml -o flow.png",
    "release": "standard-version",
    "test": "jest --runInBand --verbose --coverage",
    "test-watch": "jest --runInBand --watch"
  },
  "semistandard": {
    "ignore": [
      "examples/*/dist/**/*.*"
    ]
  },
  "types": "typings.d.ts",
  "version": "4.0.4"
}
```

**Comment by jacekkarczmarczyk** [comment] 2020-06-22 17:49
Faced the same issue, I don't have `html-webpack-plugin` directly in `package.json`, it's used by `@vue/cli`
```
$ yarn why html-webpack-plugin
yarn why v1.19.0
[1/4] Why do we have the module "html-webpack-plugin"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "html-webpack-plugin@4.3.0"
info Reasons this module exists
   - "favicons-webpack-plugin" depends on it
   - Hoisted from "favicons-webpack-plugin#html-webpack-plugin"
info Disk size without dependencies: "324KB"
info Disk size with unique dependencies: "6.09MB"
info Disk size with transitive dependencies: "17.37MB"
info Number of shared dependencies: 53
=> Found "@vue/cli-service#html-webpack-plugin@3.2.0"
info This module exists because "@vue#cli-service" depends on it.
Done in 1.21s.
```

**Comment by gabrielenivaura** [comment] 2020-07-24 14:53
Same here.

vue/cli: 2.9.6
favicons-webpack-plugin: 3.0.1
html-webpack-plugin: 4.3.0

**Comment by jantimon** [comment] 2020-07-27 10:56
Can you please try favicons-webpack-plugin 4.1.0 or newer?  
It will provide a better error message explaining which webpack version and file has been used

**Comment by gabrielenivaura** [comment] 2020-07-27 20:14
I'm still receiving same error:

`FaviconsWebpackPlugin - This FaviconsWebpackPlugin version is not compatible with your current HtmlWebpackPlugin version.
Please upgrade to HtmlWebpackPlugin >= 4 OR downgrade to FaviconsWebpackPlugin 2.x
found html-webpack-plugin 4.3.0 at /Users/XXXXXX/Documents/workspace/xxxxxx/node_modules/html-webpack-plugin/package.json
MacBook-Pro-di-XXXXX:xxxxxx XXXXX$ npm info html-webpack-plugin version
4.3.0
MacBook-Pro-di-Gabriele:xxxxxxxx gabrielechesi$ npm info favicons-webpack-plugin version
4.2.0`

**Comment by jantimon** [comment] 2020-07-28 12:49
Thanks for the feedback 👍  
So it seems to use the correct version 🤔 

The problem is somewhere here:
https://github.com/jantimon/favicons-webpack-plugin/blob/ed6c0217e349675d09ab456139b96918ef6d727a/src/index.js#L229-L232

Could you please try to  add a console.log statement to line 230 in `/Users/XXXXXX/Documents/workspace/xxxxxx/node_modules/faviocns-webpack-plugin/index.js` ?

e.g. 

```js
console.log("1", HtmlWebpackPlugin)
console.log("2", typeof HtmlWebpackPlugin.getHooks)
console.log("3", typeof require('html-webpack-plugin').getHooks)
```

**Comment by gabrielenivaura** [comment] 2020-07-28 15:04
Hi jantimon,

getHooks static is undefined and i think i understood the problem. I'm using vue-cli package that include cli-service and this last one require "html-webpack-plugin": "^3.2.0" as dependency. I think the build is using that dependency instead of the 4.
I tried to replacing the cli-service module with the 4.0.0 and i got errors. So i think latest version of cli-service doesn't work with latest version of html-webpack-plugin and build is using this one.
Is it possible to include inside your node_modules the updated version of html-webpack-plugin and use that?

Thanks for support!

**Comment by jantimon** [comment] 2020-07-28 16:23
In theory we might extend the `FaviconsWebpackPlugin` to allow specifying the plugin version to use:

```js
new FaviconsWebpackPlugin({
  HtmlWebpackPlugin: require('html-webpack-plugin'),
  // ...
})
```

But unfortunately it would not inject the favicons into the html-webpack-plugin 3.2 instances.

**Comment by jantimon** [comment] 2021-02-06 07:45
will be fixed by https://github.com/vuejs/vue-cli/issues/6109

**Closed** 2021-02-12 09:55 UTC
