### ISSUE TITLE
Malformed filepaths and output options ignored in 'light' mode

### ISSUE THREAD

**Issue by NoiSek** [jantimon/favicons-webpack-plugin#162] opened 2019-08-23 01:14 UTC
When in light mode (i.e. development), the `publicPath` or `outputPath` options are ignored if set and the file output is double-nested.

**Steps to reproduce**
- Set `WebpackConfig.mode` / `NODE_ENV` to 'development', or change the `FaviconsPlugin.mode` to 'light'
- Set Webpack's `output.publicPath` value to `somedir/foo` 
- Set Plugin's `publicPath` value to `somedir/bar` as per the README.
- Build the project
- Observe the generated file path

**Expected**
Setting a `FaviconsPlugin.publicPath` value of `somedir/bar` will generate `somedir/bar/<favicon>` as the output file.

**Actual**
Setting a `FaviconsPlugin.publicPath` value of `somedir/bar` will generate `somedir/foo/somedir/foo/<favicon>` as the output file.

In addition to the double nesting, doesn't seem like you can override that behavior in order to fix it while in light mode.

**Comment by anitagraham** [comment] 2019-09-09 09:19
Thanks for the workaround of using `mode: webapp` to generate a good path

**Comment by jantimon** [comment] 2019-09-16 06:22
This was probably fixed with favicons-webpack-plugin@1.0.2

Can you please give it a try?
(might require a hard refresh in the browser)

**Comment by anitagraham** [comment] 2019-09-17 02:30
Great: the icon is now generated in `assets/<favicon>`.

The `prefix` setting is working, but  `outputPath` seems to be ignored. 

I was only using `prefix` and `outputPath` as potential work arounds, so I am happy.
👍

**Comment by NoiSek** [comment] 2019-09-17 23:34
Can confirm that it's generating normally under `assets/<favicon>` now, but it still seems to ignore your `webpack.publicPath` and `faviconsPlugin.outputPath` settings when in development mode.

**Comment by YaMecca** [comment] 2019-09-23 06:41
Please call mom 9109297627

**Comment by jantimon** [comment] 2019-09-24 11:40
Looking at the code I would say that the public path is used - can you spot any bug here?

https://github.com/jantimon/favicons-webpack-plugin/blob/a3f75b13f060c14e27461eccbfdf8ec0158b5206/src/index.js#L126

**Comment by Tofandel** [comment] 2019-11-04 16:53
You need to check for undefined on compilation.outputOptions.publicPath and not boolean
Eg: `const webpackPublicPath =  typeof compilation.outputOptions.publicPath !== 'undefined' ? compilation.outputOptions.publicPath : '/'; `

Because the publicPath can be an empty string and that needs to be preserved

**Comment by Tofandel** [comment] 2019-11-04 21:08
#173 Will fix this issue

**Comment by DenisSemionov** [comment] 2019-11-21 09:11
Voting for this issue! I just need the generated path to be './icons/favicon.ico', but it continues to add the '/' (slash) symbol all the time.

![image](https://user-images.githubusercontent.com/32300784/69323532-9598f300-0c4f-11ea-9bd7-ca2ead651dda.png)

![image](https://user-images.githubusercontent.com/32300784/69323542-9b8ed400-0c4f-11ea-80e5-8025369dca36.png)

**Comment by Tofandel** [comment] 2019-11-21 11:02
@DenisSemionov You can use my patch in the meantime, the issue is fixed there

In package.json:
```
  "devDependencies": {
    "favicons-webpack-plugin": "git://github.com/Tofandel/favicons-webpack-plugin.git#next",
}
```

**Comment by jantimon** [comment] 2019-11-27 09:04
Right now we have the following cases:


| mode              | webpack publicPath   | favicons-webpack-plugin publicPath  |
| ------------- |----------------------| -------------------------------------- |
| webapp         | undefined | undefined |
| webapp         |''| undefined |
| webapp         | undefined| '' |
| webapp         | ''| '' |
| webapp         | 'some/path' (relative)| 'another/path' (relative) |
| webapp         | '/some/path' (relative)| 'another/path' (relative) |
| webapp         | '/some/path' (absolute)| '/another/path' (absolute) |
| webapp         | 'some/path' (relative))| '/another/path' (absolute) |
| webapp         | '/some/path' (absolute)| '' |
| webapp         | 'some/path' (relative))| '' |
| webapp         | '/some/path' (absolute)| undefined |
| webapp         | 'some/path' (relative))| undefined |


| mode              | webpack publicPath   | favicons-webpack-plugin publicPath  |
| ------------- |----------------------| -------------------------------------- |
| light         | undefined | undefined |
| light         |''| undefined |
| light         | undefined| '' |
| light         | ''| '' |
| light         | 'some/path' (relative)| 'another/path' (relative) |
| light         | '/some/path' (relative)| 'another/path' (relative) |
| light         | '/some/path' (absolute)| '/another/path' (absolute) |
| light         | 'some/path' (relative))| '/another/path' (absolute) |
| light         | '/some/path' (absolute)| '' |
| light         | 'some/path' (relative))| '' |
| light         | '/some/path' (absolute)| undefined |
| light         | 'some/path' (relative))| undefined |

what would be the correct outcome for every case?

**Comment by jantimon** [comment] 2019-12-28 08:18
Fixed and released as https://www.npmjs.com/package/favicons-webpack-plugin/v/2.0.0

**Closed by jantimon** 2019-12-28 08:18 UTC
